trigger:
    - master
    - develop

pool:
    vmImage: 'ubuntu-latest'

jobs:
    - job: Develop
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
      steps:
          - task: Npm@1
            name: Install_Dependencies
            inputs:
                command: 'install'
          - task: Npm@1
            name: Build_Development
            inputs:
                command: 'custom'
                customCommand: 'run build:dev'
          - publish: $(System.DefaultWorkingDirectory)/build
            artifact: build
    - job: Production
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      steps:
          - task: Npm@1
            name: Install_Dependencies
            inputs:
                command: 'install'
          - task: Npm@1
            name: Build_Production
            inputs:
                command: 'custom'
                customCommand: 'run build:prod'
          - publish: $(System.DefaultWorkingDirectory)/build
            artifact: build
